### ISSUE TITLE
Could I reconstruct my picture to different shape? 

### ISSUE THREAD

**Issue by ucaswindlike** [HongwenZhang/DaNet-3DHumanReconstruction#6]
What a great work.
I want to reconstruct my person in pictures to 2 different shape( a fat mesh and a thin mesh), how can I make it?
Thanks a lot

**Comment by HongwenZhang** [comment]
Hi, ucaswindlike. In the case of using pre-defined shapes, you can simply handcraft a fat shape and a thin shape of the SMPL model and use them in place of the predicted ones.

**Comment by ucaswindlike** [comment]
> Hi, ucaswindlike. In the case of using pre-defined shapes, you can simply handcraft a fat shape and a thin shape of the SMPL model and use them in place of the predicted ones.

sorry I did not find thee part to change the shape.

**Comment by HongwenZhang** [comment]
By simply modifying the `beta_pred` [here](https://github.com/HongwenZhang/DaNet-3DHumanReconstruction/blob/master/demo.py#L106), you can use any handcrafted shapes as you need.

**Comment by ucaswindlike** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            when I run the code, pickle.load the smpl pkl fole. it came out the error:KeyError: '\x00', Was the file wrong?
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                237673991
                            
                    
                        
                            
                                    237673991@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/10/2020 16:13，Hongwen Zhang<notifications@github.com> wrote： 



By simply modifying the beta_pred here, you can use any handcrafted shapes as you need.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ucaswindlike** [comment]
Thanks for your reply, I want to save the mesh as .obj file. How can I modify the code
