### ISSUE TITLE
Error of smplx

### ISSUE THREAD

**Issue by lintianwei-blog** [HongwenZhang/DaNet-3DHumanReconstruction#8]
Hi, thanks for your released codes. When I running the demo.py, it cames some errors:

File "/ssd1/vis/lintianwei/3d/DaNet-3DHumanReconstruction-master/models/smpl.py", line 7, in <module>
    from smplx.body_models import ModelOutput
ImportError: cannot import name 'ModelOutput'

Do you know how to fix this?

**Comment by HongwenZhang** [comment]
Hi, this error seems to be raised by a mismatched version of the smplx package. Which version of smplx do you use?
Version 0.1.13 should be fine.
`pip install smplx==0.1.13`
