### ISSUE TITLE
How do you prepare and render partial IUV image?

### ISSUE THREAD

**Issue by wangzheallen** [HongwenZhang/DaNet-3DHumanReconstruction#9]
How do you prepare and render both global IUV images and partial IUV ground truth?

For example: how do you use
https://github.com/HongwenZhang/DaNet-3DHumanReconstruction/blob/master/utils/part_utils.py
and how to get the masks for rendering?

**Comment by HongwenZhang** [comment]
Hi, I use this function [verts2uvimg](https://github.com/HongwenZhang/DaNet-3DHumanReconstruction/blob/429a37d335aae595804dbece356a27d10165d432/models/danet/smpl_regressor.py#L370) to render global IUV images. An example of usage can be found in the [demo.py](https://github.com/HongwenZhang/DaNet-3DHumanReconstruction/blob/master/demo.py#L151) code.
After obtaining global IUV images, we can crop partial IUV images accordingly in an STN fashion like [here](https://github.com/HongwenZhang/DaNet-3DHumanReconstruction/blob/429a37d335aae595804dbece356a27d10165d432/models/danet/iuv_estimator.py#L224).
The rendered IUV images can be interpreted as I, U, and V channels using iuv_img2map as shown [here](https://github.com/HongwenZhang/DaNet-3DHumanReconstruction/blob/master/models/danet/iuv_estimator.py#L97).
We do not use the PartRenderer for IUV rendering.

**Comment by HongwenZhang** [comment]
Now, the global IUV images can be generated by [IUV_Renderer](https://github.com/HongwenZhang/DaNet-3DHumanReconstruction/blob/master/utils/renderer.py#L202). It supports batched operation.
